name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run-ci:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
      ROPSTEN_RPC_URL: ${{ secrets.ROPSTEN_RPC_URL }}
      RINKEBY_RPC_URL: ${{ secrets.RINKEBY_RPC_URL }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install Deps
        run: yarn install
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      # solidity tests
      - name: Run tests
        run: yarn test
      # checks
      - name: Hardhat compile
        run: npx hardhat compile --show-stack-traces
      - name: Run lint check
        run: yarn lint
      # test deployment
      - name: Deploy contracts
        run: npx hardhat deploy --show-stack-traces
